export const products = [
    {
      id: 1,
      name: 'Pink Basic Hoodie',
      price: 'RS 2000',
      href: '#',
      imageSrc: 'https://images.unsplash.com/photo-1516195851888-6f1a981a862e?ixlib',
      imageAlt: "Women Clothing",
      description : "A tee Shirt",
    },
    {
      id: 2,
      name: 'Pink Basic Hoodie',
      price: 'RS 2000',
      href: '#',
      imageSrc: 'https://images.unsplash.com/photo-1516195851888-6f1a981a862e?ixlib',
      imageAlt: "Women Clothing",
      description : "A tee Shirt",
    },
    {
      id: 3,
      name: 'Pink Basic Hoodie',
      price: 'RS 2000',
      href: '#',
      imageSrc: 'https://images.unsplash.com/photo-1516195851888-6f1a981a862e?ixlib',
      imageAlt: "Women Clothing",
      description : "A tee Shirt",
    },
    {
      id: 4,
      name: 'Pink Basic Hoodie',
      price: 'RS 2000',
      href: '#',
      imageSrc: 'https://images.unsplash.com/photo-1516195851888-6f1a981a862e?ixlib',
      imageAlt: "Women Clothing",
      description : "A tee Shirt",
    },
    {
      id: 5,
      name: 'Pink Basic Hoodie',
      price: 'RS 2000',
      href: '#',
      imageSrc: 'https://images.unsplash.com/photo-1516195851888-6f1a981a862e?ixlib',
      imageAlt: "Women Clothing",
      description : "A tee Shirt",
    },
    {
      id: 6,
      name: 'Pink Basic Hoodie',
      price: 'RS 2000',
      href: '#',
      imageSrc: 'https://images.unsplash.com/photo-1516195851888-6f1a981a862e?ixlib',
      imageAlt: "Women Clothing",
      description : "A tee Shirt",
    },
    // More products...
  ]